### ISSUE TITLE
无法上传文件的原因

### ISSUE THREAD

**Issue by denghongcai** [ChieveiT/swala#1]
在进行Request转换时如果加入

```
$files = isset($request->files) ? $request->files : array();
```

并且将创建SymfonyRequest的语句改为

```
new SymfonyRequest($get, $post, array(), $cookie, $files/*$_FILES*/, $server);
```

上传文件是可以正常进行的，然而在调用Validator进行校验时会出现校验无法通过的情况，这是由于Validator使用了`is_uploaded_file`内置函数进行文件来源的判断，Swoole并没有支持

解决方法可以是把Validator在用户级别覆盖或者使用别的校验方式

**Comment by ChieveiT** [comment]
非常感谢你的建议：）

其实加入$files参数之前有考虑过，不过没太多时间进行完整的依赖审查，不敢乱加，大概就是怕出现Validator这种情况

今天下午查看了一下is_uploaded_file的源码

``` c
/* {{{ proto bool is_uploaded_file(string path)
   Check if file was created by rfc1867 upload */
PHP_FUNCTION(is_uploaded_file)
{
    char *path;
    size_t path_len;

    if (!SG(rfc1867_uploaded_files)) {
        RETURN_FALSE;
    }

    if (zend_parse_parameters(ZEND_NUM_ARGS(), "s", &path, &path_len) == FAILURE) {
        return;
    }

    if (zend_hash_str_exists(SG(rfc1867_uploaded_files), path, path_len)) {
        RETURN_TRUE;
    } else {
        RETURN_FALSE;
    }
}
```

文件合法性判断涉及SG(rfc1867_uploaded_files)和SG(rfc1867_uploaded_files)的设置，这两个估计是内核层的东西T_T，用户层无法访问，要不然这合法性就能通过用户层代码hack了，所以用户层的替换方案跑不通

而swoole文档也没文件合法性的检验方案（其实我是想提issue，但估计会被人无视，php图片上传本身就很没存在感啊...

最终的解决答复：如果能相信自己的用户层代码，没有太明显的注入点，干脆别验证了，一起愉快地裸奔吧...

最最终再次感谢：）（妈蛋哥在github上终于不是小透明了！T_T

**Comment by denghongcai** [comment]
是的，rfc1867_uploaded_files是PHP内核层的哈希表，存储通过PHP的sapi上传的文件信息，做安全校验的

我也觉得给swoole提issue比较好- -

祝贺成为有issue的男人！
