### ISSUE TITLE
L4.2未知支持否？

### ISSUE THREAD

**Issue by goodspb** [ChieveiT/swala#3]
项目是在L4.2的，不知道是否支持~

**Comment by ChieveiT** [comment]
呃，不支持的，5.0和4.2相差太多。其实这项目一开始是在4.2上试验的，最后看5.0代码结构好了很多，激进折腾一下，就变成支持5.0了...这东东玩票性质居多，不成熟，真实的业务环境还是建议用fpm+laravel:)

Anyway，感谢关注～

**Comment by goodspb** [comment]
@ChieveiT By the way ，4.2上其实可以做~我们现在有个4.2的项目跑在swoole上，主要是高并发的地方都放swoole，其余后台FPM

**Comment by denghongcai** [comment]
其实用Swoole的话如果没有其他IO操作情况下对Laravel性能提升很大，有上百倍；但是如果有MySQL或者其他IO操作的话其实和fpm的差距并不大...聊表安慰

**Comment by goodspb** [comment]
@denghongcai 我们主要感觉是Laravel加载的内容太多，框架的消耗其实也很巨大，每一次的new xxx ，并发起来很占CPU，所以swoole加laravel是挺好的方向呢。

**Comment by denghongcai** [comment]
瓶颈不是每次的new…而是框架的依赖太多太多了，fpm执行完整体销毁的策略使得每次请求的时间基本都耗费在了加载框架上而不是自己的业务代码上

如果不把Laravel的I/O操作重写成异步方式，那么每次做I/O的时候都把Swoole的event loop给阻塞了
我这里比较激进，生产上Laravel 5.1跑在Swoole上，用的PHP7，性能还是个问题

还是准备以Lumen为基础fork个给swoole用的版本出来
